# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://apps.alecrem.com/koyomito
title: Koyomito
email: ale@alecrem.com
author: Alejandro Cremades
description: > # "Write an awesome description for your new site here. 
  Koyomito is a calendar app written completely in Japanese, that helps you in your immersion into Japan's culture.
copyright: 'Copyright &copy; 2017 Alejandro Cremades. All rights reserved.'
credits: 'Send an email to Alejandro from his website <a href="https://alecrem.com/">Alecrem</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/alecrem
  - title: instagram
    url: https://www.instagram.com/karawapo/
  - title: youtube
    url: https://www.youtube.com/karawapo
  - title: facebook
    url: https://www.facebook.com/alecrem
